Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-11, with the labels that each got.

#154 (hack/release.sh) allow target platform(s) override
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#155 upgrade to latest debian-base version
  deployment/docker/Dockerfile
  test/e2e/e2e.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#157 fix a few bugs in scripts
  hack/release.sh
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 support to run e2e with kind
  hack/e2e.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
