Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-05, with the labels that each got.

#97 typo
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#101 rename StorageClass name from local-fast to local-storage
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#96 Support cross-building and multi-arch image
  .dockerignore
  Makefile
  deployment/docker/Dockerfile
  hack/release.sh
  hack/run-e2e.sh
  third_party/multiarch/qemu-user-static/LICENSE
  third_party/multiarch/qemu-user-static/README.kubernetes
  third_party/multiarch/qemu-user-static/register/qemu-binfmt-conf.sh
  third_party/multiarch/qemu-user-static/register/register.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#102 add retry for getting node when setup
  cmd/local-volume-provisioner/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
