Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-06, with the labels that each got.

#104 bug fix: Copy docker config to a writable directory
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Add faq for containerzed kubelet
  docs/faqs.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#110 Files are symbolic links in secret volume of the container
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 Clarify that scripts to start Kubernetes clusters are in Kubernetes repository
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#120 Fix GCE-latest testing
  Gopkg.lock
  deployment/kubernetes/example/default_example_provisioner_generated.yaml
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 Allow user to configure additional PV labels
  cmd/local-volume-provisioner/main.go
  pkg/common/common.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#115 Update helm docs
  helm/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#122 Use rbacv1
  Gopkg.lock
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
