Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-09, with the labels that each got.

#144 release 2.3.3
  CHANGELOG.md
  README.md
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 Fix changelog links
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 controller/discoverer: add readiness check
  Gopkg.lock
  cmd/local-volume-provisioner/main.go
  docs/provisioner.md
  pkg/controller/controller.go
  pkg/discovery/discovery.go
  test/e2e/e2e_test.go
  vendor/k8s.io/apiserver/pkg/server/healthz/doc.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
