Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-04, with the labels that each got.

#71 Update examples and README for GA
  README.md
  examples/local-reader.yaml
  examples/local-statefulset-affinity.yaml
  examples/local-statefulset-anti-affinity.yaml
  examples/local-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#73 Support for PodSecurityPolicies
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/templates/pod-security-policy.yaml
  helm/provisioner/templates/provisioner-cluster-role-binding.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#80 Fix hack/release.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#82 Add operations/faqs docs and layout change
  README.md
  TODO.md
  docs/best-practices.md
  docs/faqs.md
  docs/getting-started.md
  docs/operations.md
  docs/provisioner.md
  helm/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#83 More faqs
  docs/faqs.md
  docs/operations.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#84 More faqs
  docs/faqs.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#86 Release 2.3.1
  CHANGELOG.md
  README.md
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#88 Unset DOCKER_CONFIG in hack/run-e2e.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 release 2.3.2
  CHANGELOG.md
  README.md
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#90 Filter out unstable tags
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#93 Make pod security policy in Helm chart valid
  helm/provisioner/templates/pod-security-policy.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
