Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-03, with the labels that each got.

#61 Use k8s.io/klog
  Gopkg.lock
  Gopkg.toml
  provisioner/cmd/main.go
  provisioner/pkg/cache/cache.go
  provisioner/pkg/common/common.go
  provisioner/pkg/controller/controller.go
  provisioner/pkg/deleter/deleter.go
  provisioner/pkg/deleter/jobcontroller.go
  provisioner/pkg/discovery/discovery.go
  provisioner/pkg/discovery/discovery_test.go
  provisioner/pkg/metrics/metrics.go
  provisioner/pkg/metrics/metrics_test.go
  provisioner/pkg/populator/populator.go
  provisioner/pkg/util/volume_util.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/LICENSE
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/mount/LICENSE
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/util/doc.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 Mount /dev in cleanup job
  Gopkg.lock
  provisioner/pkg/deleter/jobcontroller.go
  test/e2e/e2e_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#67 Grant gcloud user the ability to create roles in GKE
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#70 should not swallow error when listing mounter
  provisioner/pkg/discovery/discovery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
