Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2019-01, with the labels that each got.

#31 Migrate the rest of e2e tests from k/k repo
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#32 Support gke provider and docs how to run e2e tests
  README.md
  hack/e2e.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 Fix e2e tests against GKE
  Gopkg.lock
  hack/e2e.sh
  test/e2e/e2e.go
  vendor/cloud.google.com/go/AUTHORS
  vendor/cloud.google.com/go/CONTRIBUTORS
  vendor/cloud.google.com/go/LICENSE
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/golang.org/x/oauth2/google/appengine.go
  vendor/golang.org/x/oauth2/google/appengine_gen1.go
  vendor/golang.org/x/oauth2/google/appengine_gen2_flex.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/oauth2/google/sdk.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/jwt/jwt.go
  vendor/google.golang.org/appengine/appengine.go
  vendor/google.golang.org/appengine/appengine_vm.go
  vendor/google.golang.org/appengine/errors.go
  vendor/google.golang.org/appengine/identity.go
  vendor/google.golang.org/appengine/internal/app_identity/app_identity_service.pb.go
  vendor/google.golang.org/appengine/internal/modules/modules_service.pb.go
  vendor/google.golang.org/appengine/namespace.go
  vendor/google.golang.org/appengine/timeout.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#26 Cleanup gce/gke examples
  README.md
  helm/examples/gce.yaml
  helm/generated_examples/gce.yaml
  provisioner/deployment/kubernetes/gce/class-local-ssds.yaml
  provisioner/deployment/kubernetes/gce/provisioner_generated_gce_ssd_count.yaml
  provisioner/deployment/kubernetes/gce/provisioner_generated_gce_ssd_volumes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#34 Add hack/release.sh to do releasing automatically
  Makefile
  hack/release.sh
  provisioner/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 Give GCP project default zone
  hack/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 Update docs for 2.3.0
  CHANGELOG.md
  README.md
  provisioner/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 fix the test with fake.ClientSet
  Gopkg.lock
  provisioner/pkg/deleter/deleter_test.go
  provisioner/pkg/discovery/discovery_test.go
  provisioner/pkg/util/api_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#39 Improve releasing script
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#37 Update CI links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#42 Fix bug in helm
  helm/generated_examples/gce-retain.yaml
  helm/provisioner/templates/provisioner.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#45 Save reports in ARTIFACTS directory
  Gopkg.lock
  hack/run-e2e.sh
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#43 Fix helm rendering issue
  helm/generated_examples/baremetal-prometheus.yaml
  helm/provisioner/templates/provisioner.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 Remove Namespace field for ClusterRoleBinding/ClusterRole
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/templates/provisioner-cluster-role-binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#46 use PROVISIONER_E2E_IMAGE to specify e2e image to test
  hack/e2e.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
