Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2020-08, with the labels that each got.

#210 install all kubetest2 binaries
  hack/e2e.sh
  hack/lib.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#212 gke: use non-default network
  hack/e2e.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#211 OWNERS: move dhirajh to emeritus_approvers
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#208 Update chart
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/generated_examples/helm2/baremetal-affinity.yaml
  helm/generated_examples/helm2/baremetal-cleanbyjobs.yaml
  helm/generated_examples/helm2/baremetal-default-storage.yaml
  helm/generated_examples/helm2/baremetal-nodeselector.yaml
  helm/generated_examples/helm2/baremetal-priority-critical.yaml
  helm/generated_examples/helm2/baremetal-priority-noncritical.yaml
  helm/generated_examples/helm2/baremetal-prometheus.yaml
  helm/generated_examples/helm2/baremetal-resyncperiod.yaml
  helm/generated_examples/helm2/baremetal-tolerations.yaml
  helm/generated_examples/helm2/baremetal-with-resource-limits.yaml
  helm/generated_examples/helm2/baremetal-without-rbac.yaml
  helm/generated_examples/helm2/baremetal.yaml
  helm/generated_examples/helm2/gce-pre1.9.yaml
  helm/generated_examples/helm2/gce-retain.yaml
  helm/generated_examples/helm2/gce.yaml
  helm/generated_examples/helm2/gke.yaml
  helm/provisioner/templates/configmap.yaml
  helm/provisioner/templates/daemonset.yaml
  helm/provisioner/templates/servicemonitor.yaml
  helm/provisioner/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XXL

#213 Add daemonset.podAnnotations and daemonset.podLabels to Helm chart
  helm/README.md
  helm/provisioner/templates/daemonset.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#215 add notes for rancher extra binds
  docs/faqs.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
