Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2020-05, with the labels that each got.

#187 feat: add namePattern field in discovery PV
  pkg/common/common.go
  pkg/common/common_test.go
  pkg/discovery/discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#188 doc: add github template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#189 feat: add helm support on namePattern field
  helm/README.md
  helm/provisioner/templates/configmap.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#190 test: add travis CI to get code coverage data
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#191 doc: add code coverage
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#192 doc: add namePattern example
  deployment/kubernetes/example/default_example_provisioner_generated.yaml
  docs/provisioner.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#193 update get-started page with AKS
  docs/getting-started.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#196 Fix typo in README.md title
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
