Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2020-06, with the labels that each got.

#198 fix namePattern syntax error
  helm/provisioner/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#200 Fix blkdiscard script
  CHANGELOG.md
  deployment/docker/scripts/blkdiscard.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#205 Add affinty to helm chart
  helm/README.md
  helm/examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/helm2/baremetal-affinity.yaml
  helm/provisioner/templates/daemonset.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
