Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2020-02, with the labels that each got.

#130 Add notes about using Filesystem on block devices
  docs/operations.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#169 docs on configuration and upgrading
  README.md
  docs/provisioner.md
  docs/upgrading.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#170 add notes about volumeMode and fix TOC
  docs/operations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#174 Remove old cleanup status before create new pv
  pkg/discovery/discovery.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#178 release v2.3.4
  CHANGELOG.md
  README.md
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-namespace.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
