Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2020-09, with the labels that each got.

#218 Fix for command example for getting disk UUID
  docs/operations.md
Labels: approved, cncf-cla: yes, kind/bug, kind/documentation, lgtm, ok-to-test, size/XS

#219 improv: Add opt-out for `/dev` volume in the chart
  helm/README.md
  helm/provisioner/templates/daemonset.yaml
  helm/provisioner/templates/psp.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#221 improv: Allow unprivileged provisioner in chart
  helm/README.md
  helm/provisioner/templates/daemonset.yaml
  helm/provisioner/templates/psp.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#222 handle DeletedFinalStateUnknown object when receiving PV delete event
  pkg/populator/populator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
