Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2021-04, with the labels that each got.

#244 Update image registry to gcr
  Makefile
  cmd/utils/update-pv-to-beta/Makefile
  cmd/utils/update-pv-to-beta/README.md
  cmd/utils/update-pv-to-beta/deployment/kubernetes/update-pv-to-beta.yaml
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#248 (docs) update Helm README.md
  helm/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#246 Duplicate volume guard
  pkg/cache/cache.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/populator/populator.go
  pkg/util/volume_util_unsupported.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#250 Update base image to debian buster 1.6.0
  deployment/docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
