Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2022-03, with the labels that each got.

#290 Fix gce bootstrap script guide
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, tide/merge-method-squash, size/XS, ok-to-test

#292 ClusterRole system:persistent-volume-provisioner replaced with a custom ClusterRole with the same contents minus permissions to access PVCs
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/development-gce.yaml
  helm/generated_examples/development-gke.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke.yaml
  helm/generated_examples/helm2/baremetal-affinity.yaml
  helm/generated_examples/helm2/baremetal-cleanbyjobs.yaml
  helm/generated_examples/helm2/baremetal-default-storage.yaml
  helm/generated_examples/helm2/baremetal-nodeselector.yaml
  helm/generated_examples/helm2/baremetal-priority-critical.yaml
  helm/generated_examples/helm2/baremetal-priority-noncritical.yaml
  helm/generated_examples/helm2/baremetal-prometheus.yaml
  helm/generated_examples/helm2/baremetal-resyncperiod.yaml
  helm/generated_examples/helm2/baremetal-tolerations.yaml
  helm/generated_examples/helm2/baremetal-with-resource-limits.yaml
  helm/generated_examples/helm2/baremetal-without-rbac.yaml
  helm/generated_examples/helm2/baremetal.yaml
  helm/generated_examples/helm2/development-gce.yaml
  helm/generated_examples/helm2/development-gke.yaml
  helm/generated_examples/helm2/eks-nvme-ssd.yaml
  helm/generated_examples/helm2/gce-pre1.9.yaml
  helm/generated_examples/helm2/gce-retain.yaml
  helm/generated_examples/helm2/gce.yaml
  helm/generated_examples/helm2/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/templates/rbac.yaml
  test/e2e/e2e_test.go
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/XXL

#295 Bump Dockerfile debian image to v1.10.0
  deployment/docker/Dockerfile
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/XS

#299 Update release instructions, helm chart action only works with tags
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/helm-chart-release.yml
  Makefile
  RELEASE.md
  cloudbuild.yaml
  hack/release.sh
Labels: kind/cleanup, approved, size/M, cncf-cla: yes, lgtm
