Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2022-10, with the labels that each got.

#338 fix: set admin user in windows image build
  .github/workflows/codespell.yml
  deployment/docker/Dockerfile.Windows
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS

#341 Modify daemon set to add path /dev
  deployment/kubernetes/example/default_example_provisioner_generated.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#342 fix: CVE-2022-32149
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XXL
