Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2023-12, with the labels that each got.

#410 fix: do not try to get node for non-local PVs
  pkg/node-cleanup/controller/controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#413 feat: add allowedTopologies for storage class in helm
  helm/provisioner/templates/rbac.yaml
  helm/provisioner/templates/storageclass.yaml
  helm/provisioner/values.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm, ok-to-test

#422 cleanup: print error message for cleanup errors
  pkg/node-cleanup/controller/controller.go
  pkg/node-cleanup/deleter/deleter.go
Labels: approved, size/S, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test
