Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2023-07, with the labels that each got.

#385 Add controller to clean up stale PVs/PVCs when a Node is deleted
  cmd/cleanup/main.go
  pkg/cleanup/controller/controller.go
  pkg/cleanup/controller/controller_test.go
  pkg/cleanup/deleter/deleter.go
  pkg/cleanup/deleter/deleter_test.go
  pkg/common/common.go
  pkg/common/common_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL, ok-to-test

#391 Add documentation and release image for cleanup controller
  Makefile
  README.md
  cloudbuild.yaml
  cmd/node-cleanup/Dockerfile
  cmd/node-cleanup/main.go
  deployment/kubernetes/example/node-cleanup-controller/deployment.yaml
  deployment/kubernetes/example/node-cleanup-controller/rbac.yaml
  docs/node-cleanup-controller.md
  hack/release.sh
  pkg/node-cleanup/controller/controller.go
  pkg/node-cleanup/controller/controller_test.go
  pkg/node-cleanup/deleter/deleter.go
  pkg/node-cleanup/deleter/deleter_test.go
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L, ok-to-test

#393 Flatten helm keys common, daemonset. Add CHANGELOG file for the helm chart
  hack/verify-generated.sh
  helm/CHANGELOG.md
  helm/README.md
  helm/examples/baremetal-affinity.yaml
  helm/examples/baremetal-cleanbyjobs.yaml
  helm/examples/baremetal-nodeselector.yaml
  helm/examples/baremetal-priority-critical.yaml
  helm/examples/baremetal-priority-noncritical.yaml
  helm/examples/baremetal-resyncperiod.yaml
  helm/examples/baremetal-tolerations.yaml
  helm/examples/baremetal-with-resource-limits.yaml
  helm/examples/baremetal-without-rbac.yaml
  helm/examples/development-gce.yaml
  helm/examples/development-gke.yaml
  helm/examples/gce-pre1.9.yaml
  helm/examples/gce-retain.yaml
  helm/examples/gce.yaml
  helm/examples/gke-nvme-ssd-block-raid.yaml
  helm/examples/gke.yaml
  helm/generated_examples/gce-pre1.9.yaml
  helm/generated_examples/gke-mauricio.yaml
  helm/generated_examples/helm2/baremetal-affinity.yaml
  helm/generated_examples/helm2/baremetal-cleanbyjobs.yaml
  helm/generated_examples/helm2/baremetal-default-storage.yaml
  helm/generated_examples/helm2/baremetal-nodeselector.yaml
  helm/generated_examples/helm2/baremetal-priority-critical.yaml
  helm/generated_examples/helm2/baremetal-priority-noncritical.yaml
  helm/generated_examples/helm2/baremetal-prometheus.yaml
  helm/generated_examples/helm2/baremetal-resyncperiod.yaml
  helm/generated_examples/helm2/baremetal-tolerations.yaml
  helm/generated_examples/helm2/baremetal-with-resource-limits.yaml
  helm/generated_examples/helm2/baremetal-without-rbac.yaml
  helm/generated_examples/helm2/baremetal.yaml
  helm/generated_examples/helm2/development-gce.yaml
  helm/generated_examples/helm2/development-gke.yaml
  helm/generated_examples/helm2/eks-nvme-ssd.yaml
  helm/generated_examples/helm2/gce-pre1.9.yaml
  helm/generated_examples/helm2/gce-retain.yaml
  helm/generated_examples/helm2/gce.yaml
  helm/generated_examples/helm2/gke-mauricio.yaml
  helm/generated_examples/helm2/gke.yaml
  helm/provisioner/templates/_helpers.tpl
  helm/provisioner/templates/configmap.yaml
  helm/provisioner/templates/daemonset_linux.yaml
  helm/provisioner/templates/daemonset_windows.yaml
  helm/provisioner/templates/psp.yaml
  helm/provisioner/templates/rbac.yaml
  helm/provisioner/templates/serviceaccount.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, kind/cleanup, approved, cncf-cla: yes, lgtm, size/XXL

#388 feat: add enableWindows as helm values for Windows DaemonSet creation
  helm/README.md
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/development-gce.yaml
  helm/generated_examples/development-gke.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke-nvme-ssd-block-raid.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/templates/daemonset_windows.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL, ok-to-test

#387 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  cmd/utils/update-helm-values-pre-v2.2.0/pkg/chartutil/values.go
  go.mod
  go.sum
  pkg/common/common.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: kind/cleanup, approved, size/XL, cncf-cla: yes, lgtm, ok-to-test

#394 Stop publishing images to quay.io
  hack/release.sh
  helm/README.md
  helm/generated_examples/baremetal-namespace.yaml
  test/e2e/e2e_test.go
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/L

#395 Update release process
  RELEASE.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#392 Add v2.5.0 CHANGELOG
  CHANGELOG.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#396 Update CHANGELOG for 2.6.0
  CHANGELOG.md
  README.md
  helm/CHANGELOG.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#397 Add multi-arch manifest for node cleanup controller
  Makefile
  cmd/node-cleanup/Dockerfile.Windows
  hack/release.sh
Labels: approved, size/M, cncf-cla: yes, lgtm, ok-to-test
