Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2023-08, with the labels that each got.

#399 Add metrics for cleanup controller
  cmd/node-cleanup/main.go
  deployment/kubernetes/example/node-cleanup-controller/deployment.yaml
  docs/node-cleanup-controller.md
  pkg/metrics/node-cleanup/metrics.go
  pkg/node-cleanup/controller/controller.go
  pkg/node-cleanup/deleter/deleter.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XXL, ok-to-test

#401 feat(helm): Added support for additional volumes
  helm/README.md
  helm/examples/additional-volumes.yaml
  helm/generated_examples/additional-volumes.yaml
  helm/provisioner/templates/daemonset_linux.yaml
  helm/provisioner/templates/daemonset_windows.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#402 Bump default helm chart image to v2.6.0
  go.mod
  helm/CHANGELOG.md
  helm/generated_examples/additional-volumes.yaml
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke-nvme-ssd-block-raid.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
  helm/provisioner/values.yaml
  vendor/modules.txt
Labels: kind/cleanup, approved, size/M, cncf-cla: yes, lgtm

#404 Update changelog with v2.6.0 generated notes
  CHANGELOG.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L
