Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2024-11, with the labels that each got.

#463 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#461 Helmchart add imagePullSecrets
  helm/README.md
  helm/provisioner/templates/daemonset_linux.yaml
  helm/provisioner/templates/daemonset_windows.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm, ok-to-test

#462 Update values.yaml
  helm/provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#466 helmchart: allow parameterize storageClass.provisioner
  helm/README.md
  helm/examples/baremetal-provisioner.yaml
  helm/generated_examples/baremetal-provisioner.yaml
  helm/provisioner/templates/storageclass.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#465 fix: Do not clean PV's with a deletion timestamp
  pkg/deleter/deleter.go
  pkg/deleter/deleter_test.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#464 Update blkdiscard call in blkdiscard.sh
  deployment/docker/Dockerfile
  deployment/docker/scripts/blkdiscard.sh
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
