Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2024-12, with the labels that each got.

#470 fix: CVE-2024-45338
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/internal/socket/zsys_openbsd_ppc64.go
  vendor/golang.org/x/net/internal/socket/zsys_openbsd_riscv64.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#446 [Feature] Allow additional selector terms to be defined in storage config
  helm/provisioner/templates/configmap.yaml
  pkg/common/common.go
  pkg/common/common_test.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/node-cleanup/controller/controller.go
  pkg/node-cleanup/deleter/deleter.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#473 doc: update doc with 2.7.0 version
  README.md
  deployment/kubernetes/example/default_example_provisioner_generated.yaml
  helm/README.md
  helm/generated_examples/additional-volumes.yaml
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-provisioner.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke-nvme-ssd-block-raid.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/values.yaml
Labels: approved, kind/documentation, cncf-cla: yes, size/L

#474 chore: upgrade to go1.23
  go.mod
  go.sum
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
  vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt
Labels: approved, size/XL, cncf-cla: yes

#449 feat: add hostPID for linux daemonset container
  helm/README.md
  helm/generated_examples/additional-volumes.yaml
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-provisioner.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/development-gce.yaml
  helm/generated_examples/development-gke.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke-nvme-ssd-block-raid.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/templates/daemonset_linux.yaml
  helm/provisioner/values.yaml
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm, ok-to-test

#475 chore: upgrade to go1.22
  go.mod
Labels: approved, cncf-cla: yes, size/XS
