Repository kubernetes-sigs/sig-storage-local-static-provisioner, pull requests merged in 2025-04, with the labels that each got.

#487 chore: use go1.24
  go.mod
  pkg/discovery/discovery.go
Labels: kind/cleanup, approved, cncf-cla: yes, size/XS

#488 chore: use registry.k8s.io instead of gcr.io/google-containers
  examples/gke-daemonset-raid-disks.yaml
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#489 test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#490 chore: bump to go1.23.8 to fix image build failure
  go.mod
Labels: approved, cncf-cla: yes, size/XS, kind/failing-test

#491 doc: use official canary image in examples
  go.mod
  helm/examples/development-gce.yaml
  helm/examples/development-gke.yaml
  helm/generated_examples/development-gce.yaml
  helm/generated_examples/development-gke.yaml
Labels: approved, size/S, kind/documentation, cncf-cla: yes

#493 fix: CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, approved, cncf-cla: yes, size/XXL

#495 Release helm chart v2.8.0
  helm/generated_examples/additional-volumes.yaml
  helm/generated_examples/baremetal-affinity.yaml
  helm/generated_examples/baremetal-cleanbyjobs.yaml
  helm/generated_examples/baremetal-default-storage.yaml
  helm/generated_examples/baremetal-nodeselector.yaml
  helm/generated_examples/baremetal-priority-critical.yaml
  helm/generated_examples/baremetal-priority-noncritical.yaml
  helm/generated_examples/baremetal-prometheus.yaml
  helm/generated_examples/baremetal-provisioner.yaml
  helm/generated_examples/baremetal-resyncperiod.yaml
  helm/generated_examples/baremetal-tolerations.yaml
  helm/generated_examples/baremetal-with-resource-limits.yaml
  helm/generated_examples/baremetal-without-rbac.yaml
  helm/generated_examples/baremetal.yaml
  helm/generated_examples/development-gce.yaml
  helm/generated_examples/development-gke.yaml
  helm/generated_examples/eks-nvme-ssd.yaml
  helm/generated_examples/gce-retain.yaml
  helm/generated_examples/gce.yaml
  helm/generated_examples/gke-nvme-ssd-block-raid.yaml
  helm/generated_examples/gke.yaml
  helm/provisioner/Chart.yaml
Labels: kind/cleanup, approved, cncf-cla: yes, lgtm, size/L, ok-to-test
